version: '3.1'

services:

  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    command: [--auth]
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_container:/data/db

  api:
    build:
      context: PixelPlanner
      dockerfile: PixelPlanner.Api/Dockerfile
    ports:
      - 81:81
    depends_on:
      - mongodb

    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:81

volumes:
  mongodb_data_container: